# -*- coding: utf-8 -*-
"""PythonVariables

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AiAyg0mdUMRM8dmPG_pD0KZ98ELdV_5P
"""

name=input("enter your working software company name")
print('my working software comopany is',name)

name=input("enter your nick name")
'my nick name is',name



type(name)

# variables
# what is variables?
# memory allocation
# x=&10
x=81
print(x)
print(type(x))

x='nexminds'
print(x)

print(type(x))

x='WiseIntern','nexminds','IBM'
print(x)

print(type(x))

print(id(x))

x=1,2,3,4,5
print(x)

type(x)

x=3.14
print(x)

type(x)

print(type(x))

#x=2,2.14,'nexminds',2+4j,True,False
#print(x)

#print(type(True))

#print(type(2+4j))

#x

#x

x

y=2+4j,True,24

type(y)

y=2+4j

type(y)

x=y=z=2,'python',3.89,True

print(x)

print(type(x))

print(y)

print(z)

# int x;
x=int(input('enter the value of x\n'))
print('The value of x is\n',x)

x=str(input('enter any string'))
print('my given string',x)

a=int(input())
b=int(input())
c=int(input())
print(a,b,c)

x,y=bool(input("enter x,y boolean values"))
print(x,y)

x=100
x+=1
print(x)

x=100
x=101
x+=91
print(x)

