# -*- coding: utf-8 -*-
"""PythonPrintFunctions

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KcZfAZHifj90CaPmE4aZH9TLQbmreCQP
"""

# print function or method

print("hello nextminds")

print("my name is sreeram")

print('my name is sreeram')

"hello world!"

# type method()
type(print)

